sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: GyQ4Wt/iM5mbRTdOli53CRAOi/Zj6GR+oAox9DbvvG8Uq34jrHCt4nxfWrGvHBZgbH8cd56EmMDwoQS9qInqJRucwX3xg24eVO6QKD+WFDEKhGpCliDO9MO3lJslfJPa3i6sK6xj9xr36rDT0pcoQ56IjVY3ZoHYsM6zoSO3HKspEdYpzkXSfv6VFrJ7BIMp5LenGhmP7yf9g7tWZzPOJrUM2SvD95MCv6OwYgcXArJyKJ4lwTv9/cayJWyuEhmv7iP/38qX3miGw/rKg4T0py0o5jMdP6DHx3HhcYg1xP/av2vjWhI2bage1XkM0EFc3Cv1qQMef9slDtSe/1s4erNzI1zzVrlwYBfpC2KcQKgjKpW9absq6Z3TD3Nyotk2N6xLW7CoWlsjBufrvlwEGrD8RzYreMR0CPN2R2u/a1VETjt2B4Ers5uOduLVVFf52L6VuAOPEKsDXytbWcTx+eDAnWRDNCSUWC8ym0vr3PBd4ZoCDsjxviYXxwvacC9rKvQsyKJr/lx2T845FojzhVCcAD+XHZr1p9qaoCAuo5qxkjLmrV2TPmjGFKtkgkcMxqWCp8YCTSOU5ndHOl2889vA0tufugw0wRix6L9f6mw1ivOnsTt8rrpe5gBTfqtMo6bN2ZHeBPCs2SWQmgfF+rE3LiBDuUnVBemAaVfD+JY=
  - secure: aBGsprxCHFe686jdi+6sektzsJnvwMPny/PaFenxE2AO7Sz4oEx2haZAnd4L0Rmuz6ZzppgPgcXMEmsQRpoq1+MTmEEi45qp5wj4unzViogzt5YalUhWpCyLLzEpV2CRVF78uDsUWm1Yyqu/8zkS1wM/sLoMJM0QMRarF3JcqaVmd7iAmfC7IBQL7dnwAJiVTnxhjqqJHh+yaVC0Ak5FdwNtSGZ5EWIA7xp9N+MiWVlyiry7e98om0S1IzYsKQJWGP31ZEAjyORTjjn5NV/2LVLcVB835oEYPv5p3ISPJbGoyV0TZBIbArTOFicmOYaiUJJ6tIj8PmKXOWmo4MeB42yaxYNM+VB1G7PpNpSH+dsjPOAN4xN5wU7IFA0RUdUxr2RDZRaeKm07kfpPrHoR6NY/JnHVdA0DKvi/FrnBrSbRSMZFM2wxJTsZwG1FIeF1CGRBfCiAcfhE9NgNLORYvk8BBpmwpV6f1Z38jlMjAUHvH3Uf+uH6rWI8pHQhvwgCy4L4uQoBlqCvcTOopPQ3ee6NIb73uLeQS+Qf121wwLla6Hn3fydYVJuUMAid7vNM1pTUDnUHShj/RPDoWLURATxyhBrJxKrku3l88pTKrh5udFxn/T/mJgJugCYUQFP5EB0cXiMIgXRlD8YwD4k4RXAQMShFBPNNvhtV7lSMhK0=
  - secure: J1dMWuJF5CN9/7cI7ZxbijyA1Ur9Oyrto3QhMKmALetuPz3Q2KeYZtblmDmQ9T5hIfFDwpU4/EHGsDCQIJmD8pl7C2qv+xoKlNZQLZqA95k8CIgGSmOEfFnLocWl1Im7N017AuVa9KaAbIvtEhwaHkrKBYN+Dws8phRodjWWbrRG2K4MzYV3qlFrphWVAkySUmUNvsaPDqUq6+Nza4FMLwht/ZTh9COTGYoUmNkMJ3SX1fieVPAOhUc0kdvoIUcji6I9NSChne8Sxy0Eto5H4Sy9WvugMQm3nQDgp7bBWrCgd2BZzyyhAIQEOPddIxzg4LbhtadgIrrmgyG4iu/p9HfLcAta1ELVsFbd9TA3+ac3qX1+hLlCevL5r1QF2DR5pUG3vsskcVaYyaIS77Jdw+DscHhoQfA2rvsWHRgJKgosGPxuxitIxCS8W35F8dB3HudocoxRAWCnzcRYcJinPTUoAtFacrANMc/oC/TAB5TVlEDAERNZUbTFeQER0abpqv7L0gyjX3qh/UWrRFEe8lTjwLDuiBYKt6thieOpkFbSpMO09gO9rZdobOv8gaNoRlk9aIN5XTZd0sax1KFsn+hLPp30l/YthfMK6vhebVRKPmdTgwKYx7X+RgBNz8X8HaGmtUxLqTW7K0950qWbMsAOlcp2ibPP4y2K5qFpOlg=
  - secure: ckApEZEw5VLneCKmtMCmrikyYqzgfWLAPETvHXDYFFTjjo2bAJl9lo0cdOyN1paWRr+GkzinRl2Bvdq7YJn9Oh+0kfwlgtJkw5PxHRkYTrpRE7DtxPLb9seo56893Mgo+jdT0NZri5+BRjT3P/Ha3Isr+rpCJfzIICpeanB0j78GWIp6ZwdXr9LfqikLRx5KL9+DpR6X8MziQ74omwIvq3prck7+bwKFK3DVyhahlaMLrd1n1zUs6V7NbjvCvKYqit25RxOx1vMUw7uvnvzyvFxN2/i73Nv8eYrJAlSfkwNWxLkTi0BpjT5MAWdkOKeeNJXmfe/bnrsZdJc/uEHL6SqEfv5KnX0GhLVfZDrB5TWeHG3o0hO5D9/GGYt2Y6erXfb1jknzaUH6uCO8nTkZFsq/L3+6VB/VgAqbhBXK7rcr9QIjaA6T2Hq6e4MGE0ngHdJl3ILLMgbjm3rl67qgUuXeaOs90svRiZW1QKIdJ92oa1jYCy8OYxh8i036Mfv0A7gWWkeS6YX88R18cT0rbWS2wBK6pEzpdYfprsKkto1xYmbY6OIPjVV7CZOYNsw4xsTZpe3FL3/CZcl8n+uwhTKXNgMwantuV3AZmWpv7r1XnYH0CsB4UMBAj4w8Oki2v+pAnVETjFHHJT6FrecNVB+pu2cajl+2ZSZIG5gcgn0=
