sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Fik/4G7bsdTGnUBhLKWlebLWRkr1QkGDtCaqhC165+QJjLE71Q6gCWxKazTuFThqsP+r71R0Hk1fF+zIK8ZbKuRB+wr5UCWS5EuI3t1gKbZK77zDRR7lLmJNXvug6rTMymYXJq3PRDlB9s9KXKFRiLZfDG0eupwHCzlRuemoZBKH/E2rHSASSd8LeJ8w2jauNrYq06aEYpeYpeyK4kHd00mR5GpcMML/xAs1uFh2dBxAkrajpFGEtf5OggBPc4EYP5P0wGG0lk7DTgBDp1xolrn75FDp9ybqswjLcHX68LbAOz6C/1I/03+c4JVSN9ppVdm7DnRKGvfQ35UgbUkKImqjheUOFlLC+BbkxPHgY4R/EseDrZAO26DYFNvblgtjbuoE1uvuHbUxFAnKvNHLEd8Iubw4Sb8rPY4hm8yhb4N5jTJEjm6Lk0gSQFphSjQRk1N+/NRJNfXSgpzMcEGOeI5yHypXTgC0oi4I/0jmPxxbqyiSO1h71cvWRcc7yGOZdU4YZemURQ0F2AvfuSKpt7j3X3VSYPOfDX82PRNYPXFy3mAKScSXAxsvdRvyWp4vHL3KpcJuSc0D0eK0aBlswTPoIEZ9/wPujWuci9DK0ABimevF3SnMBU4c6F3yRNQhGFvwCZo/lYscaLbVDfxgFuS6SSHij8NcHO9Kc8adSRo=
  - secure: eyPyHQTG7AJJRHdhXnI0tSXlNdkwoHGnHzTKfvr1BguwL/diIY8o88HsUPx1CPwX2mPTSVo1UKeB8Qg50WeeiwbLggFXHwOqWBgoQpltmRS486ZnUmqstLBJ5Y5fJ50zNq2td7SEnx7Dbur8ZOZfIqORMFwP88G/1BAzk8EO2n22XC+6PxwgsP8U9A/x6hSprYKtnd1epopdgKEWRDpA47JnbsQtiTZYJyGj+V6+tPN1e8uhgDk7P5wzOSRp6JiSEL/TUMdDcPGYRKwYoW7YeQ5LXWKgEm+BxueSSiNPdhpjP2IJyw3N//jkaE7gZ9KFpDPHHd7891Bw4ar3wiUWmkY5IkPEJJ8tvyNdkmFums8VOjj/ndPcOYhH+LIOWAendg/Sk+P5xHWI7p9s5JOiKmhdbg8djZd9RR2/SeA1jwRpAKm+LXP0q6JixOJG7POHgy2b212fpaEt7iqHxz03saYvIve7UcL2uK2L5cMAATVicbDyFJ7mqGitElyjfjELnPvFsZXrwGEtU91SqnfCLNKpZ3lF78XfAekd5GZLOJoR/Q3fbHnpROCZKRvpLCYxBnpUG7FEnJrQB48mIIzhK6DVgAkffyp9dtsDFOXXWYthslmSorP3jfW6gt888TEO9cQQ6NPPw2QMU+rAY4i2dYP16iSYXy7Gzmk+exA8vHI=
  - secure: jziDVYejHPUU3f9r9NIPofcMW4fY2c/I0bKNTfJTq11lOGEcVG5lJDaTmO8tVZMutepYLaZPIucMZX86eIITSe/Id152VYY/FBYLEUvlj9+CZ5szZ4AQkh8DR7PQ+DZ12ynVxZokNG1gKfLKNLrKxWSp+xnPbL6bXQDNNrUIK2PV0czqox2M0pHZgo7pzEhYvVEh7SF6M2aw2Hp7fsw0oRKWYfnkwPLzHsXX5BwSmxPjO9D4Lgx1l7E0Ys7oJhFMqCuVqcQ12aoAqxXrBatiEXmHQ07JFezN9sRc4zNKKiUbgzFcQc//fPUh4uaeUdvzFJGOLrtgoALbwUcA59hIEOuiEdL5+fMdmN7Ow9FxwTBJU5qpMvQRNTLXHlNviiU/4tQ+bEpPPN3xRDDPU8eVjw25dOv+gojssXzhNZiJGhoLw9JtNjxKRDECtayM7JV8cu+2glXFDC3lBC+zXhKeploKLUlyETF4pFfKBwWr2qexc7YZX2FSpumuprsAZNvaXJJkQ79pscRXrXFb0Egu+zgx7lG0r0LoC+PqmoIK5iMTD4P1g2ccrc9GkmdgtDNcXXnXYyBFWQrKwDcxTdODbfhcX8FTCm9DyZwROXA+e4pA/qU61JNTBczLxcfyHc7xIFJfhCnY8Mg6kALEkhrUfz/hi/uX2UQI6ZT1b1Q0N/o=
  - secure: DZj+6nH7k8ZxwJGfR2zS2UtNJzPasL4md5yaxOSCAMrCR+vVFL67++ZMsDqck+L+qsQFv7zXD0Tn7y1eYAI4jw4/58Il/AcX3vshZH9J1EOaNnypjAwqm1xDdyNSSlvk36/MBt8lVbx0x7qPTYDjlMSuKEUCkTVD1bV3knAy5dksmX15XbTrzTZUTUiQHkE4DvMMojOM97v98KgtZo9NA9mHSw9W7OY5emKPBGMG99rWhJGM/Qj3be56lLCoPxgRYd/qYqh0Xwv8UovGg6E5l5AgJEpkZkOWhACWHkb77as3wMVufreDd1O+hEgGNwmjG+fI7c4wOlwRtyBlGKW5HDPNptruSrGUXe0Rya2TuFQJG11tbDNB0lKNO6b8wGZ9JtuKOpUNFSPq0vDxElWWWMAG+N/wJSotS1omgFeEIo/nKoTtCRlM3LY5cibbQw0nDZcc9bcetx5ow6zkKj3f9qKgGNGDOiuEUfZpKqamTyfTRd7eZKb1Ee+YNHgaHsH87hH7xIHQJdhZvPni4MlhlRzvWCyQ5lAY57aXHIkETK+SNpIafEETmhHajHIao29OMAjpxBmQ0IU31ACx9eJZQsuM3giHLXTRSAS62qVOaw7pybRI2bfr4ZbT1hTP4cW8M3G8arTXlSkFVqGbhoT6MVT4stLm45SIgmpjOqtnahE=
